### ISSUE TITLE
Adding a Class - add a class

### ISSUE THREAD

**Issue by kuhaku4** [mucsci-students/2024sp-420-Java2#2]
Add a Class
User Adds a class
Class is added
Primary: @CullenIsntHere 
Secondary: @kuhaku4 
Difficulty: Rykard
Actual Difficulty: Godrick
Time: 15 minutes.

**Comment by kuhaku4** [comment]
rykard

**Comment by jrlease-03** [comment]
rykard level

**Comment by CullenIsntHere** [comment]
Rykard
